/**
 * HomeScreen styles — extracted from HomeScreenLegacy.js as Phase E.3.1
 * (2026-05-02). Pure presentation styles, shared by the container's dead
 * legacy renderHeader fragment and the future presentation file. Module
 * scope captures `selectedVariant` and `screenWidth` are defined here
 * locally so the styles work standalone.
 */

import { StyleSheet, Dimensions } from 'react-native';
import Config from '../../utils/safeConfig';

const { width: screenWidth } = Dimensions.get('window');
const selectedVariant = Config?.APP_VARIANT || 'rgxresearch';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F0F0',
    },
    headerBP: {
        marginTop: 25,
        flex: 1,
    },
    headerTitle: {
        fontSize: 20,
        fontFamily: 'Satoshi-Bold',
        color: '#000',
    },
    modalOverlay: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    backButton: {
        marginTop: 10,
        flexDirection: 'row',
        alignContent: 'center',
        alignItems: 'center',
        marginHorizontal: 15,
    },
    bespokeTabRow: {
        flexDirection: 'row',
        marginHorizontal: 15,
        marginTop: 12,
        marginBottom: 6,
    },
    bespokeTabPill: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 3,
        alignItems: 'center',
        justifyContent: 'center',
        marginHorizontal: 2,
        height: 40,
    },
    bespokeTabPillText: {
        fontSize: 14,
        fontFamily: 'Poppins-Medium',
    },
    headerContainer: {
        flexDirection: 'column',
        alignItems: 'center',
        alignSelf: 'center',
        paddingBottom: 0,
        overflow: 'hidden',
        width: '100%',
    },
    StockTitle: {
        fontSize: 18,
        color: '#1A1A1A',
        fontFamily: 'Poppins-SemiBold',
    },
    StockTitlebelow: {
        fontSize: 12,
        fontFamily: 'Satoshi-Bold',
        marginBottom: 5,
        color: 'grey',
    },
    viewAllText: {
        fontSize: 10,
        marginTop: 2,
        marginHorizontal: 5,
        fontFamily: 'Poppins-Regular',
        color: '#1F7AE0',
    },
    viewAll: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        fontFamily: 'Poppins-Medium',
        marginBottom: 5,
        borderWidth: 1,
        borderRadius: 3,
        borderColor: '#1F7AE0',
    },
    borderGradient: {
        borderRadius: 10,
        padding: 2,
        marginHorizontal: 15,
        marginTop: 15,
    },
    linearGradient: {
        borderRadius: 8,
        paddingHorizontal: 15,
        paddingVertical: 0,
        flexDirection: 'row',
        alignItems: 'center',
        overflow: 'hidden',
    },
    searchBarContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        borderRadius: 60,
    },
    searchBar: {
        fontFamily: 'Satoshi-Regular',
        textAlignVertical: 'center',
        alignContent: 'space-between',
        alignItems: 'center',
        alignSelf: 'center',
        flex: 1,
        fontSize: 13,
        padding: 0,
        borderRadius: 30,
        marginHorizontal: 5,
        paddingVertical: 6,
        color: 'white',
    },
    textContainer: {
        alignItems: 'flex-start',
        alignSelf: 'center',
        backgroundColor: 'transparent',
        paddingRight: 0,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
    },
    headerText: {
        fontFamily: 'ObviouslyNarrow-Black',
        fontSize: selectedVariant === 'arfs' ? 45 : 45,
        lineHeight: 55,
        color: '#fff',
    },
    subText: {
        fontFamily: 'Satoshi-Bold',
        fontSize: 10,
        color: '#fff',
        alignContent: 'flex-start',
        alignItems: 'flex-start',
    },
    tabContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    filterButton: {
        backgroundColor: 'white',
        borderRadius: 20,
        marginLeft: 10,
        paddingVertical: 2,
        paddingHorizontal: 15,
        borderColor: '#E6E6E6',
        borderWidth: 1,
    },
    filterButtonText: {
        fontSize: 12,
        paddingVertical: 3,
        marginBottom: 1,
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        textAlign: 'center',
        textAlignVertical: 'center',
        fontFamily: 'Satoshi-Regular',
        color: 'black',
    },
    activeTabButton: {
        borderWidth: 1.5,
        borderColor: '#000',
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        backgroundColor: '#002A5C1A',
    },
    inactiveTabButton: {
        backgroundColor: '#fff',
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        borderWidth: 1.5,
    },
    activeTabButtonText: {
        color: '#000',
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
    },
    inactiveTabButtonText: {
        color: '#00000080',
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    labelContainer: {
        alignContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    labelText: {
        fontFamily: 'Satoshi-Medium',
        color: '#888',
        marginBottom: 5,
        fontSize: 14,
    },
    magnusHeaderContainer: {
        alignItems: 'flex-start',
        paddingBottom: 12,
        paddingHorizontal: 12,
    },
    magnusTitleSection: {
        alignItems: 'flex-start',
    },
    magnusTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 4,
    },
    magnusMainText: {
        fontFamily: 'Satoshi-Bold',
        fontSize: 22,
        color: '#fff',
    },
    magnusResearchText: {
        fontFamily: 'ObviouslyNarrow-Black',
        fontSize: 36,
        lineHeight: 42,
        color: '#FFFFFF',
        letterSpacing: -0.2,
        textShadowColor: 'rgba(255, 255, 255, 0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    magnusSecondaryText: {
        fontFamily: 'ObviouslyNarrow-Black',
        fontSize: 36,
        lineHeight: 42,
        color: 'rgba(255, 255, 255, 0.95)',
        letterSpacing: -0.2,
        marginLeft: 2,
    },
    magnusCredentials: {
        alignItems: 'center',
        alignContent: 'center',
        alignSelf: 'center',
    },
    magnusBadgeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        alignContent: 'center',
        alignSelf: 'center',
        marginBottom: 8,
    },
    magnusAIBadge: {
        borderRadius: 16,
        paddingHorizontal: 14,
        paddingVertical: 6,
        marginRight: 10,
        shadowColor: '#FFD700',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 4,
        elevation: 3,
    },
    magnusAIBadgeText: {
        fontFamily: 'Satoshi-Bold',
        fontSize: 13,
        color: '#FFFFFF',
        letterSpacing: 0.5,
        fontWeight: '700',
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 1,
    },
    magnusVerified: {
        borderRadius: 16,
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderWidth: 0,
    },
    magnusVerifiedText: {
        fontFamily: 'Satoshi-Bold',
        fontSize: 13,
        color: '#FFFFFF',
        letterSpacing: 0.3,
        fontWeight: '700',
    },
    magnusTagline: {
        fontFamily: 'Satoshi-Medium',
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
        letterSpacing: 0.1,
        lineHeight: 16,
        marginLeft: 2,
    },
    carouselWrapper: { paddingLeft: 15 },
    carouselContainer: { paddingRight: 15 },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
        width: screenWidth - 30,
    },
    emptyText: {
        fontFamily: 'Satoshi-Regular',
        fontSize: 14,
        color: '#888',
    },
    emptyStateContainer: {
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        width: screenWidth - 60,
        marginVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    emptyStateIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#F0F4FF',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 15,
    },
    emptyStateTitle: {
        fontFamily: 'Satoshi-Bold',
        fontSize: 16,
        color: '#333',
        marginBottom: 8,
    },
    emptyStateText: {
        fontFamily: 'Satoshi-Regular',
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        lineHeight: 20,
    },
    blogCard: {
        backgroundColor: '#fff',
        borderRadius: 10,
        overflow: 'hidden',
        width: 260,
        marginRight: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        marginBottom: 10,
        elevation: 3,
        marginLeft: 11,
    },
    blogImage: {
        width: '100%',
        height: 150,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
    },
    blogTitle: {
        fontSize: 18,
        fontFamily: 'Satoshi-Bold',
        color: 'white',
    },
    textOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        paddingHorizontal: 15,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'flex-start',
        backgroundColor: 'rgba(0, 0, 0, 0.3)',
    },
    timestampContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 20,
    },
    timestampText: {
        fontSize: 12,
        color: 'white',
        fontFamily: 'Satoshi-Regular',
        marginLeft: 5,
    },
    videoCard: {
        borderRadius: 10,
        overflow: 'hidden',
        width: 300,
        marginRight: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 5,
        marginLeft: 11,
    },
    videoThumbnail: {
        width: '100%',
        height: 150,
        borderRadius: 10,
    },
    videoInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
    },
    videoTitle: {
        fontSize: 14,
        lineHeight: 15,
        fontFamily: 'Satoshi-Medium',
        fontWeight: 'normal',
        color: 'black',
    },
    videoDetails: {
        fontSize: 12,
        color: '#888',
        fontFamily: 'Satoshi-Light',
    },
    pdfCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 10,
        marginRight: 15,
        width: 280,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        borderBottomWidth: 1,
        borderBottomColor: '#E6E6E6',
        marginLeft: 11,
    },
    pdfContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    pdfIcon: {
        width: 40,
        height: 50,
    },
    pdfCardContent: {
        marginLeft: 10,
        flex: 1,
        flexShrink: 1,
    },
    pdfCardTitle: {
        fontSize: 16,
        fontFamily: 'Satoshi-Medium',
        color: '#333',
        flexShrink: 1,
    },
    pdfCardDescription: {
        fontSize: 12,
        fontFamily: 'Satoshi-Light',
        color: '#858585',
        marginTop: 5,
    },
    downloadButton: {
        padding: 10,
    },
    videoModalBackground: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    videoModalContent: {
        width: '90%',
        backgroundColor: '#000',
        borderRadius: 12,
        overflow: 'hidden',
    },
    videoModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 15,
        backgroundColor: '#111',
    },
    videoModalTitle: {
        color: '#fff',
        fontFamily: 'Satoshi-Bold',
        fontSize: 16,
        flex: 1,
        marginRight: 10,
    },
    emptyStateWrapper: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 15,
        minWidth: screenWidth - 30,
    },
    viewButton: {
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
        marginTop: 5,
        alignSelf: 'flex-start',
    },
    viewButtonText: {
        fontSize: 10,
        fontFamily: 'Satoshi-Medium',
        color: '#666',
    },
});
